package com.meta_force.meta_force.data.model

/**
 * Request object for sending a message to the AI chat.
 *
 * @property message The text message to send to the AI.
 * @property sessionId Optional session ID to continue an existing conversation.
 */
data class ChatMessageRequest(
    val message: String,
    val sessionId: String? = null
)

/**
 * Response received from the AI chat.
 *
 * @property sessionId The ID of the current chat session.
 * @property response The content of the AI's response, including any generated plans.
 */
data class ChatResponse(
    val sessionId: String,
    val response: AiResponseContent
)

/**
 * Encapsulates the textual message and optional plan in an AI response.
 *
 * @property message The text message returned by the AI.
 * @property plan An optional [AiGeneratedPlan] if the AI generated a workout or diet.
 */
data class AiResponseContent(
    val message: String,
    val plan: AiGeneratedPlan? = null
)

/**
 * Represents a plan generated by the AI, such as a workout or a diet.
 *
 * @property type The type of plan, typically "WORKOUT" or "DIET".
 * @property name The name given to the plan.
 * @property description A brief description of what the plan entails.
 * @property days A list of [AiPlanDay] containing the daily items for the plan.
 */
data class AiGeneratedPlan(
    val type: String, // "WORKOUT" | "DIET"
    val name: String,
    val description: String,
    val days: List<AiPlanDay>
)

/**
 * Represents a single day within an [AiGeneratedPlan].
 *
 * @property dayOfWeek The index of the day (e.g., 1 for Monday).
 * @property items A list of [AiPlanItem] for this specific day.
 */
data class AiPlanDay(
    val dayOfWeek: Int,
    val items: List<AiPlanItem> // represents both exercises and meals
)

/**
 * Represents an individual item in a plan, such as an exercise or a meal.
 *
 * @property name The name of the exercise or food item.
 * @property sets Optional number of sets (for workouts).
 * @property reps Optional number of repetitions (for workouts).
 * @property quantity Optional quantity of food (for diets).
 * @property notes Additional instructions or comments for this item.
 */
data class AiPlanItem(
    val name: String,
    val sets: String? = null,
    val reps: String? = null,
    val quantity: String? = null,
    val notes: String? = null
)

/**
 * Represents a chat session with the AI.
 *
 * @property id Unique identifier for the session.
 * @property title An optional human-readable title for the session.
 * @property createdAt Timestamp of when the session was initialized.
 * @property messages The list of [ChatMessage] exchanged in this session.
 */
data class ChatSession(
    val id: String,
    val title: String?,
    val createdAt: String,
    val messages: List<ChatMessage>
)

/**
 * Represents an individual message within a [ChatSession].
 *
 * @property role The role of the sender (e.g., "user", "assistant").
 * @property content The text content of the message.
 * @property createdAt Timestamp of when the message was sent.
 */
data class ChatMessage(
    val role: String,
    val content: String,
    val createdAt: String
)

/**
 * Request object for saving a generated plan to the user's profile.
 *
 * @property plan The [AiGeneratedPlan] to be saved.
 */
data class SavePlanRequest(
    val plan: AiGeneratedPlan
)
