package com.meta_force.meta_force.data.network

import com.meta_force.meta_force.data.model.ChatResponse
import com.meta_force.meta_force.data.model.ChatMessageRequest
import com.meta_force.meta_force.data.model.ChatSession
import com.meta_force.meta_force.data.model.SavePlanRequest
import retrofit2.http.Body
import retrofit2.http.DELETE
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.Path

/**
 * Retrofit interface for AI-related API endpoints.
 */
interface AiApi {

    /**
     * Sends a chat message to the AI and receives a response content.
     *
     * @param request The [ChatMessageRequest] to send.
     * @return A [ChatResponse] with the AI's response.
     */
    @POST("ai/chat")
    suspend fun sendMessage(@Body request: ChatMessageRequest): ChatResponse

    /**
     * Retrieves all chat sessions for the current user.
     *
     * @return A list of [ChatSession] objects.
     */
    @GET("ai/sessions")
    suspend fun getSessions(): List<ChatSession>

    /**
     * Saves a plan generated by the AI to the user's records.
     *
     * @param request The [SavePlanRequest] containing the plan data.
     */
    @POST("ai/save-plan")
    suspend fun savePlan(@Body request: SavePlanRequest)

    /**
     * Deletes a specific chat session.
     *
     * @param sessionId The ID of the session to remove.
     */
    @DELETE("ai/sessions/{sessionId}")
    suspend fun deleteSession(@Path("sessionId") sessionId: String)
}
